/* Billing schema generated by a migration tool, then hand edited. */
create table invoices (
    invoice_id integer primary key,
    account_id integer not null,
    currency text not null check (currency in ('USD', 'EUR', 'GBP')),
    amount_due numeric not null,
    amount_paid numeric not null default 0,
    due_date text,
    paid_at text,

    constraint amounts_are_non_negative check (
        amount_due >= 0 and amount_paid >= 0
    ),

    CHECK (
        paid_at IS NULL OR amount_paid >= amount_due
    )
);

CREATE TABLE invoice_lines (
    invoice_id INTEGER NOT NULL,
    line_no INTEGER NOT NULL CHECK (line_no > 0),
    description TEXT NOT NULL CHECK (description <> ''),
    quantity NUMERIC NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    /* CHECK (unit_price < 1000000) -- removed pending enterprise pricing */
    CHECK (quantity > 0 AND unit_price >= 0),
    PRIMARY KEY (invoice_id, line_no)
);

-- The payments table is commented out because it references the invoices table, which is not present in the ecommerce schema.
/*
CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoices(invoice_id),
    amount NUMERIC NOT NULL CHECK (amount > 0),
    paid_at TEXT NOT NULL
    CHECK (paid_at <= date('now')),
    CHECK (amount <= (SELECT amount_due - amount_paid FROM invoices WHERE invoice_id = payments.invoice_id))    
);
*/
